name: Tinta en las Cintas
tagline: "Un mixtape colectivo."
description: "Un mixtape colectivo: Blog de música."
url: https://tintaenlascintas.co
lang: es
twitter: kandr3s
comments: false
analytics: true
analytics-id: 'UA-86791161-2'

# Social
social:
  links:
    - https://twitter.com/kandr3s

# File management
include: [".htaccess"]
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge